### ISSUE TITLE
Support 'parseSpacing' in 'PluginSettings'

### ISSUE THREAD

**Issue by NilsJacobsen** [samuelstroschein/inlang-plugin-json#14]
Reason:
- no merge conflicts after every parsing

Suggestion:
```typescript
type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
  parseSpacing?: number;
};
```

**Comment by felixhaeberle** [comment]
I think this should not be only the number, but also tab or space? Otherwise there will be a conflict because git detects tabs / spaces differently.

**Comment by samuelstroschein** [comment]
This is a duplicate of https://github.com/samuelstroschein/inlang-plugin-json/issues/2.
