### ISSUE TITLE
Placeholder doesn't work if placeholder is at the beginning of the message

### ISSUE THREAD

**Issue by NiklasBuchfink** [samuelstroschein/inlang-plugin-json#17]
Works:   
 `"one_of": "Vrijednost {field} mora biti važeća vrijednost",`
 Does not work:
 `"numeric": "{field} može sadrživati samo numeričke znakove",`
 
 Great repo to test this:
 https://github.com/NiklasBuchfink/vee-validate/tree/main
 https://inlang.com/editor/github.com/NiklasBuchfink/vee-validate

**Comment by NilsJacobsen** [comment]
https://github.com/inlang/inlang/commit/046e5847a2a8a75233be39f663a470b9bd588898

This fixed the problem.

**Comment by NilsJacobsen** [comment]
This introduced a new bug in the plugin.

**Comment by samuelstroschein** [comment]
Haha and here begins the placeholder bugfixing :D
