### ISSUE TITLE
expose how resources should be serialized

### ISSUE THREAD

**Issue by samuelstroschein** [samuelstroschein/inlang-plugin-json#2]
## Problem 

Different codebases prefer different serialization styles, see https://github.com/MichMich/MagicMirror/pull/3025#issuecomment-1412788224. 

## Solution

Expose the possibility to override the default serialization style. See https://stackoverflow.com/a/3515761

**Comment by NilsJacobsen** [comment]
Hey folks: 

working on the formatting of the json files. 
I think there are two main things that need to be added regarding the format of json files.
- serialize spacing
- flatten all keys

I suggest somthing like that:

```
export type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
  sourceFormat: {
    spacing: number;
    flatten: boolean;
  }
};
```

@NiklasBuchfink @samuelstroschein @ivanhofer

**Comment by samuelstroschein** [comment]
@NilsJacobsen What do you mean with flatten?

**Comment by ivanhofer** [comment]
We need to also consider `tabs` vs `spaces`.

**Comment by samuelstroschein** [comment]
Guys, don't complicate things. Just expose the `JSON.stringify` arguments. 


To expose serialization, you can just expose the arguments of `JSON.stringify`. 

```ts
export type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
  stringify: [replacer: Parameters<typeof JSON.stringify>[1], space: Parameters<typeof JSON.stringify>[2]]
};
```

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by NilsJacobsen** [comment]
flatten is an argument that flattens the keys in a file.
To support that: 
![image](https://github.com/samuelstroschein/inlang-plugin-json/assets/58360188/0e585494-8be1-470a-bb73-1a6aa731e033)
It is almost every second project.

Therefore I wanted to use a generell naming for it.
For what do we need the replacer?

**Comment by NilsJacobsen** [comment]
```js
export type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
  stringify?: {
    spacing?: Parameters<typeof JSON.stringify>[2];
    flatten?: boolean;
  }
};
```

**Comment by samuelstroschein** [comment]
> Actually space and flatten shoundn't be required. I would say default spacing 2 or 4 and flatten false.
What do you think? 

Agree. Everything in `stringify` is optional. 

export type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
  stringify?: {
    replacer?: Parameters<typeof JSON.stringify>[1], 
    space?: Parameters<typeof JSON.stringify>[2]]
   }
};

@NilsJacobsen What do you think about renaming `stringify` to `serialize` to illustrate that this property is defining how things are "serialized"? Adding flatten seems to be a good fit then. 

```diff
export type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
-  stringify?: {
+  serialize?: {
-    replacer?: Parameters<typeof JSON.stringify>[1], 
    space?: Parameters<typeof JSON.stringify>[2]],
+  flatten?: boolean
   }
};


```

**Comment by samuelstroschein** [comment]
@NilsJacobsen haha we prorposed the same type! Should we stick with stringify or serialize?

**Comment by NilsJacobsen** [comment]
😂 I would prefer serialize

**Comment by samuelstroschein** [comment]
@NilsJacobsen lets go with serialize then 🚀

**Comment by ivanhofer** [comment]
Another issue with the file ending: https://github.com/inlang/inlang/issues/875

**Comment by samuelstroschein** [comment]
This issue is complete. The bug @ivanhofer mentioned is tracked in https://github.com/samuelstroschein/inlang-plugin-json/issues/28#issue-1740521966
