### ISSUE TITLE
import in inlang.config.js

### ISSUE THREAD

**Issue by samuelstroschein** [samuelstroschein/inlang-plugin-json#23]
@NilsJacobsen i think you might have added this import. top level imports are not supported in the inlang config js file

https://github.com/samuelstroschein/inlang-plugin-json/blob/fb565bb59e6085ba988f667399816db3132be6ca/example02/inlang.config.js#LL1C5-L1C5

**Comment by NilsJacobsen** [comment]
by accident already removed it
