### ISSUE TITLE
{language}/*.json pathPattern not working

### ISSUE THREAD

**Issue by WarningImHack3r** [samuelstroschein/inlang-plugin-json#24]
`pathPattern`: "./src/locales/{language}/*.json" (as demonstrated in [example02](https://github.com/samuelstroschein/inlang-plugin-json/blob/main/example02/inlang.config.js#L11))
File structure: `src/locales/en/home.json` & `src/locales/fr/home.json`, both containing a single k/v pair with a common `"test"` key
`i("test")` returns nothing, even when switching languages using `switchLanguage`.

Note that `./src/locales/{language}.json` works perfectly (with the adapted file structure)

Also I make sure to `rm -r` "src/routes/inlang" whenever I change my config

**Comment by NiklasBuchfink** [comment]
@WarningImHack3r Thanks for creating the issue.
@NilsJacobsen and I are currently working on this exact issue. We have created a new [pre-release 2.3.1](https://github.com/samuelstroschein/inlang-plugin-json/releases/tag/2.3.1) for it and will be testing it tomorrow with several repos. After that we will pin it as a newest version.

Test it with your use case by pinning this version in your `inlang.config.js` and give us feedback 🙂

**Comment by WarningImHack3r** [comment]
Doesn't seem to work unfortunately :/ (`inlang-plugin-json@2.3.1`)

**Comment by NiklasBuchfink** [comment]
I will investigate it tomorrow, keep you updated here and try to provide a sample.

If you use `i18next`, we currently build a dedicated plugin for this, that will be similar to the `inlang-plugin-json`. So you can be sure, we find a solution this week.

**Comment by NiklasBuchfink** [comment]
@WarningImHack3r This problem should be fixed with the latest release and the version 2.

Additionally, the [plugin-i18next](https://github.com/inlang/plugin-i18next) has now been released.

Please reopen it if you find anything else.

**Comment by WarningImHack3r** [comment]
Unfortunately, it still does not work with my config:
```javascript
/**
 * @type {import("@inlang/core/config").DefineConfig}
 */
export async function defineConfig(env) {
	const { default: pluginJson } = await env.$import(
		"https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@latest/dist/index.js"
	);

	const { default: sdkPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.1/dist/index.js"
	);

	const { default: ideExtensionPlugin } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/ide-extension-plugin@latest/dist/index.js"
	);

	return {
		referenceLanguage: "en",
		languages: ["en", "fr"],
		plugins: [
			pluginJson({
				pathPattern: "./src/locales/{language}/*.json",
				variableReferencePattern: ["{", "}"]
			}),
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: "localStorage" }]
				}
			}),
			ideExtensionPlugin()
		]
	};
}
```

**Comment by NiklasBuchfink** [comment]
@WarningImHack3r I created a SvelteKit project with the same structure and configuration and could not get it to work either. We will try to fix this next week.

**Comment by NiklasBuchfink** [comment]
Well, now it works 😄

Check here and compare it with you project: https://github.com/NiklasBuchfink/inlang-plugin-json-24
The editor works now too: https://inlang.com/editor/github.com/[NiklasBuchfink/inlang-plugin-json-24](https://inlang.com/editor/github.com/NiklasBuchfink/inlang-plugin-json-24)

**Comment by WarningImHack3r** [comment]
What did you change to make it work? Removing the `languages` array and adding the `standardLintRules` in the config?

**Comment by WarningImHack3r** [comment]
Oh, I had to precise the file name in the key path!!! Alright, thanks a lot!
