### ISSUE TITLE
Error messages by creating a new config

### ISSUE THREAD

**Issue by jannesblobel** [samuelstroschein/inlang-plugin-json#25]
I got this error message when I created a config. This happened twice, and I can't find the Bug.  

You may have a quick fix or can explain my mistake.
I made a loom, but it should be clear if you see the pictures.  

Feel free to fix this error directly in the repo.
@NiklasBuchfink  @NilsJacobsen  I think it should be easy for you 
https://inlang.com/editor/github.com/jannesblobel/AFFiNE

<img width="1165" alt="CleanShot 2023-05-23 at 23 43 32@2x" src="https://github.com/samuelstroschein/inlang-plugin-json/assets/72493222/fd124c91-591b-4040-a377-c46536176009">

![CleanShot 2023-05-23 at 23 44 31@2x](https://github.com/samuelstroschein/inlang-plugin-json/assets/72493222/9ffcb9e1-9c25-4781-a8ae-d66d9c2e0259)

https://www.loom.com/share/b4439d32f61e49118a18f8d2e80e2d9c

**Comment by NilsJacobsen** [comment]
This will already be fixed with the next release which should be pinned today:)

**Comment by NilsJacobsen** [comment]
It's due to the dot in the end of the key
