### ISSUE TITLE
Error on trying with sveltekit

### ISSUE THREAD

**Issue by lucaskfp** [samuelstroschein/inlang-plugin-json#27]
I am getting this error in my [sveltekit project](https://github.com/lucaskfp/sveltekit-inlang-js)

![image](https://github.com/samuelstroschein/inlang-plugin-json/assets/19507510/963c30c2-6aa3-4de0-accc-3c2c5a50b3e9)

**Comment by ivanhofer** [comment]
The error message says you should take a look at https://inlang.com/documentation/sdk/configuration to learn how to set it up. Have you tried that already?
