### ISSUE TITLE
auto-detect if a resource has a new line at the end or not

### ISSUE THREAD

**Issue by samuelstroschein** [samuelstroschein/inlang-plugin-json#28]
## Problem 

See https://github.com/inlang/inlang/issues/875. 

## Proposal 

1. When reading a resource, check if the JSON file contains an empty line at the end. 
2. If a resource contains an empty line, store in `resource.metadata` that an empty line exists. 
3. Upon serializing a resource, append a new line to the file if `resource.metadata.emptyNewLine === true`.

**Comment by NilsJacobsen** [comment]
@samuelstroschein we should ship that asap, for jsonPlugin and i18next. When can we start with that? Are you still in development with the plugins? 

I see this problem at every repository.

**Comment by samuelstroschein** [comment]
@NilsJacobsen yeah still doing the cal.com i18next update. 

Feel free to move the plugin-json to the monorepo https://github.com/inlang/inlang/issues/936 and start implementing the feature there.

**Comment by NiklasBuchfink** [comment]
This is now fixed with the newest version of the `plugin-json`.

For those who come across this issue later on, here is the import for the latest version:
```js
const { default: pluginJson } = await env.$import(
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@3/dist/index.js",
)
```
