### ISSUE TITLE
Add possibility to exclude paths for parsing

### ISSUE THREAD

**Issue by NiklasBuchfink** [samuelstroschein/inlang-plugin-json#9]
## Problem
Some repositories have additional json files in the same directory as the language files. These are parsed and cause issues within the editor.

Obsidian e.g. manages its translations in the root directory within a separate repository including a `package.json`

### Expected behavior
There should be a possibility in the `inlang.config.js` to exclude certain files from the parsing.

For example like this:
```js
export async function defineConfig(env) {
	const { default: pluginJson } = await env.$import(
		'https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@2/dist/index.js'
	);

	const { default: standardLintRules } = await env.$import(
		'https://cdn.jsdelivr.net/gh/inlang/standard-lint-rules@2/dist/index.js'
	);

	return {
		referenceLanguage: 'en',
		plugins: [pluginJson({ pathPattern: '.{language}.json', ignorePaths: ['package.json', '.eslintrc.json'] }), standardLintRules()]
	};
}
```

We can specify a string array of paths to be ignored in this way to provide more flexibility. The naming `ignorePaths` can be discussed.

## Reproduce current behavior
Link to the `obsidian-translations` repo:
https://github.com/NiklasBuchfink/obsidian-translations

Open this editor link:
https://inlang.com/editor/github.com/NiklasBuchfink/obsidian-translations

`.eslintrc.json` and `package.json` are parsed as language and no message is fetched correctly.

**Comment by NilsJacobsen** [comment]
Working on that right now. @NiklasBuchfink @ivanhofer  @samuelstroschein 

Suggested new PluginSettings:

```js
export type PluginSettings = {
  pathPattern: string;
  variableReferencePattern?: [string, string];
  ignore?: string[];
};
```

can be used as:
`ignore: ['package.json', '.eslintrc.json']`

**Comment by samuelstroschein** [comment]
@NilsJacobsen yes, easiest solution!
